### ISSUE TITLE
Adding rows and columns

### ISSUE THREAD

**Issue by mroodschild** [lessthanoptimal/ejml#10]
Hello again,
I think it's important to add the ability to insert columns and rows in existing matrices, making it possible to insert a column with a value.
Thank you so much.

Look at the following example

```
public static void main(String[] args) {
        double[][] datos = {{1, 2}, {3, 4}};
        double valueToInsert = 1;

        SimpleMatrix b = new SimpleMatrix(datos);//original matrix
        SimpleMatrix c = new SimpleMatrix(datos.length, datos[0].length + 1);//new matrix with 1 more column after
        SimpleMatrix d = new SimpleMatrix(datos.length, datos[0].length + 1);//new matrix with 1 more column before
        
        c.insertIntoThis(0, 1, b);//copy matrix b in matrix c, in the position selected
        c.print();
        //insert values in the first column of the new matrix
        int size = c.numRows();
        for (int i = 0; i < size; i++) {
            c.setColumn(0, i, valueToInsert);
        }
        c.print();//matrix with new values
        
        
        d.insertIntoThis(0, 0, b);//copy matrix b in matrix d, in the position selected
        d.print();
        //insert values in the last column of the new matrix
        for (int i = 0; i < size; i++) {
            d.setColumn(size, i, valueToInsert);
        }
        d.print();//matrix with new values
    }
```

**Comment by mroodschild** [comment]
In SimpleBase would:

```
public void setColumn(int column, double value) {
        int size = mat.getNumCols();
        for (int i = 0; i < size; i++) {
                 mat.set(i, column, value);
        }
 }
```

**Comment by lessthanoptimal** [comment]
For SimpleMatrix the goal is to keep it very simple.  So it has only the bare minimum that most people need.  There are alternative ways to do that by switching to CommonOps or even the Equations interface.   Equations would provide a very elegant way to do what you've requested. 

		DenseMatrix64F a = RandomMatrices.createRandom(5,2,new Random());
		
		Equation eq = new Equation();
		eq.alias(a,"a",55.0,"value");

		eq.process("b = [a(:,0),ones(5,1)*value,a(:,1:)]");
		SimpleMatrix b = new SimpleMatrix(eq.lookupMatrix("b"));

		a.print();
		System.out.println("-----------------------");
		b.print();

**Comment by mroodschild** [comment]
I understand what you say, I just thought it facilitates a task that is very common in some cases data mining. Thank you so much.
