### ISSUE TITLE
Support Broadcasting

### ISSUE THREAD

**Issue by FlorentinD** [lessthanoptimal/ejml#101]
Broadcasting allows f.i. elementWise multiplication for matrices of different size.
A simple example would be the following:
![image](https://user-images.githubusercontent.com/15693197/95754115-dbfda300-0ca2-11eb-9c00-35bdbfcaa23d.png)

Here the vector is virtually expanded to the size of the matrix, hence avoiding the actual duplication of the vector to match the dimensions of the matrix.
The terminology seems to be introduces by NumPy (https://numpy.org/doc/stable/user/basics.broadcasting.html), but also used by TensorFlow.

**I am curious, if there are others which would be interested in this feature.**
My personal use-case was that I wanted to normalize the entries in a matrix, such that the sum per row is 1.
Hence I use `reduceRowWise()` to get the sum per row and than would need broadcasting for elementWise dividing each entry with the sum of the corresponding row.
At the moment I hard coded the last step in a helper method, but I would be cleaner to just use `elementWiseMult()`

**Comment by lessthanoptimal** [comment]
How about `apply` but provide (row,col,value) as input as an alternative to dividing by row?

**Comment by FlorentinD** [comment]
Apply variants would be another idea.
For performance I would suggest 3 ways variants then: (row, value) ; (col, value) and your suggested (row, col, value).
As I would just need to access one array instead of both in the first 2 variants

**Comment by FlorentinD** [comment]
Using `apply` is also simpler to implement, I will probably go with this approach for now :+1:

**Comment by lessthanoptimal** [comment]
If you don't beat me to it I'll add a PR for this feature today or tomorrow. FYI my plan is to do a new stable release very early in November. I would do it sooner but I don't have access to a computer I test with at the moment.

**Comment by FlorentinD** [comment]
Great, just ping me, if you would like me to review the PR :)

Tomorrow, I think I will add a power law distribution for the random sparse matrices.

**Comment by FlorentinD** [comment]
I had some wrong ideas about the random power law graph generation, and will add it at a later point.

However, I will probably beat you with the apply PR in the next hours :smile:

**Comment by FlorentinD** [comment]
implemented in #103

**Comment by lessthanoptimal** [comment]
Should we close this ticket now?

**Comment by FlorentinD** [comment]
I think the extended apply replaces implicit array expansion. Unless there is someone eager in implementing it for ease of usage, I wouldn't see a reason.
