### ISSUE TITLE
DMatrixSparseCSC.getNumElements() returns number of non zero elements

### ISSUE THREAD

**Issue by cherrywoods** [lessthanoptimal/ejml#122]
Hi, 
While using EJML I stumbled about something that might be intended, but which I find pretty counter intuitive.

In `DMatrixSparceCSC` the `getNumElements()` method returns `nz_length` (number of non zero elements or internal array size or something, not sure there), while other classes return `numRows*numCols`. The java doc that is inherited from a superclass also states that this is `numRow * numCols`. 

Personally, I think there should be a separate method that returns the number of non zero elements and this method should return what is stated in the superclass javadoc. 

Kind regards,

**Comment by FlorentinD** [comment]
Indeed, I also find this behavior inconsistent. There is already `DMatrixSparseCSC#getNonZeroLength` to return `nz_length`. 
Do you want to create a PR yourself to fix this?

**Comment by FlorentinD** [comment]
Also seeing there exists `Matrix:Sparse::getNonZeroCount` and `MatrixSparse::getNonZeroLength` both returning the same.
`getNoneZeroCount` is never used though :thinking:

**Comment by cherrywoods** [comment]
I am not very familiar with the code base, it would take me some time to change it and see what side effects it could have. I can create a PR for this once I find time for it, but I am not definitelly not insisting on me doing it :sweat_smile:

**Comment by FlorentinD** [comment]
Ok, that's understandable. I can also pick this up in the next days.

**Comment by cherrywoods** [comment]
Great, thank you!

**Comment by lessthanoptimal** [comment]
Yeah, maybe we should delete `getNonZeroLength` trying to remember if there was any reason for two functions like that.
EDIT: or `getNonZeroCount` if that's the one that's not used
