### ISSUE TITLE
binary serialization to/from .mat

### ISSUE THREAD

**Issue by ennerf** [lessthanoptimal/ejml#132]
Creating a separate issue to continue the discussion from #131

I think that a `MatrixIO.loadMatlab(String fileName)` would have to be limited a very specific file layout, e.g., maybe a single matrix variable with a specific name. It'd act similar to `MatrixIO.loadBin(String fileName)` but be interoperable with Matlab, SciPy, Julia etc.

For supporting more complex file structures it'd probably be better just to use MFL directly, e.g., what should the parser do if it finds two matrices inside a cell array inside a struct?

Do you think a 

```Java
public class MatrixIO {
    public static <T extends DMatrix> T loadMatlab(String fileName) throws IOException {
        if(!hasDependency()) {
            throw new IllegalStateException("Missing dependency: add maven coordinates");
        }
        return reflectivelyCallMethod(fileName);
    }
}
```

would be better than just writing a sentence documentation for calling `Mat5Ejml.loadMatlab(String fileName)` (doesn't exist yet, but would have to be implemented in any case) ?

**Comment by lessthanoptimal** [comment]
throw an exception and tell people to use MFL directly?  Alternatively, you could pass in a List<Matrix> and put every read into the list. Similar for `saveMatlab`

**Comment by lessthanoptimal** [comment]
`throw new IllegalStateException("Missing dependency: add maven coordinates. http://project.website.com");` if the dependency isn't there. Then if a data structure that's too complex is encountered then throw another exception saying basically that this is too complex and go to the project website for instructions on how to use MFL.

**Comment by lessthanoptimal** [comment]
I really think any variant on what we have proposed would work well as long as the user knows how to fix the situation without googling.

**Comment by ennerf** [comment]
Sounds good. I don't have time this week, but I'll try to get on this soon-ish.
