### ISSUE TITLE
help with import / Maven

### ISSUE THREAD

**Issue by ChrisNabold** [lessthanoptimal/ejml#137]
I try to run a test program from your webpage - but I failed. Something is wrong with the import statement or Maven
java: <identifier> expected

PS. I added .txt to all files because of attach restrictions

/**
 * Example showing how to construct and solve a linear system using sparse matrices
 *
 * @author Peter Abeles
 */

import java.util.Random;
import package org.ejml;

public class ExampleSparseMatrix {

    public static int ROWS = 100000;
    public static int COLS = 1000;
    public static int XCOLS = 1;

    public static void main(String[] args) {
        Random rand = new Random(234);

        // easy to work with sparse format, but hard to do computations with
        // NOTE: It is very important to you set 'initLength' to the actual number of elements in the final array
        //       If you don't it will be forced to thrash memory as it grows its internal data structures.
        //       Failure to heed this advice will make construction of large matrices 4x slower and use 2x more memory
        DMatrixSparseTriplet work = new DMatrixSparseTriplet(5,4,5);
        work.addItem(0,1,1.2);
        work.addItem(3,0,3);
        work.addItem(1,1,22.21234);
        work.addItem(2,3,6);

        // convert into a format that's easier to perform math with
        DMatrixSparseCSC Z = DConvertMatrixStruct.convert(work,(DMatrixSparseCSC)null);

        // print the matrix to standard out in two different formats
        Z.print();
        System.out.println();
        Z.printNonZero();
        System.out.println();

        // Create a large matrix that is 5% filled
        DMatrixSparseCSC A = RandomMatrices_DSCC.rectangle(ROWS,COLS,(int)(ROWS*COLS*0.05),rand);
        //          large vector that is 70% filled
        DMatrixSparseCSC x = RandomMatrices_DSCC.rectangle(COLS,XCOLS,(int)(XCOLS*COLS*0.7),rand);

        System.out.println("Done generating random matrices");
        // storage for the initial solution
        DMatrixSparseCSC y = new DMatrixSparseCSC(ROWS,XCOLS,0);
        DMatrixSparseCSC z = new DMatrixSparseCSC(ROWS,XCOLS,0);

        // To demonstration how to perform sparse math let's multiply:
        //                  y=A*x
        // Optional storage is set to null so that it will declare it internally
        long before = System.currentTimeMillis();
        IGrowArray workA = new IGrowArray(A.numRows);
        DGrowArray workB = new DGrowArray(A.numRows);
        for (int i = 0; i < 100; i++) {
            CommonOps_DSCC.mult(A,x,y,workA,workB);
            CommonOps_DSCC.add(1.5,y,0.75,y,z,workA,workB);
        }
        long after = System.currentTimeMillis();

        System.out.println("norm = "+ NormOps_DSCC.fastNormF(y)+"  sparse time = "+(after-before)+" ms");

        DMatrixRMaj Ad = DConvertMatrixStruct.convert(A,(DMatrixRMaj)null);
        DMatrixRMaj xd = DConvertMatrixStruct.convert(x,(DMatrixRMaj)null);
        DMatrixRMaj yd = new DMatrixRMaj(y.numRows,y.numCols);
        DMatrixRMaj zd = new DMatrixRMaj(y.numRows,y.numCols);

        before = System.currentTimeMillis();
        for (int i = 0; i < 100; i++) {
            CommonOps_DDRM.mult(Ad, xd, yd);
            CommonOps_DDRM.add(1.5,yd,0.75, yd, zd);
        }
        after = System.currentTimeMillis();
        System.out.println("norm = "+ NormOps_DDRM.fastNormF(yd)+"  dense time  = "+(after-before)+" ms");

    }
}

[ExampleSparseMatrix.java.txt](https://github.com/lessthanoptimal/ejml/files/6409777/ExampleSparseMatrix.java.txt)
[pom.xml.txt](https://github.com/lessthanoptimal/ejml/files/6409778/pom.xml.txt)
[EJML_test.iml.txt](https://github.com/lessthanoptimal/ejml/files/6409779/EJML_test.iml.txt)

**Comment by FlorentinD** [comment]
Hey @ChrisNabold,
I just tried to create a new project with Intelij.
Steps:
(1) Create new maven project 
(2) created a Java class under `src/main/java/ExampleSparseMatrix`
(3) Copy the example code and let Intelij fix the imports (very easy to add maven dependencies this way)

My POM looks a bit different. Not a maven expert but I think you are missing the dependencies tag:
For comparison:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>ejmlTestProject</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>org.ejml</groupId>
            <artifactId>ejml-all</artifactId>
            <version>0.40</version>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

</project>
```

The main error I can see is the import of `import package org.ejml;`. In my opinion this is an anti-pattern. Instead of importing whole packages, you should import individual classes.

My imports:
```
import org.ejml.data.*;
import org.ejml.dense.row.CommonOps_DDRM;
import org.ejml.dense.row.NormOps_DDRM;
import org.ejml.ops.DConvertMatrixStruct;
import org.ejml.sparse.csc.CommonOps_DSCC;
import org.ejml.sparse.csc.NormOps_DSCC;
import org.ejml.sparse.csc.RandomMatrices_DSCC;

import java.util.Random;
```


Hope with these changes you can get your project to run.
Would be interested in your use-case of sparse matrices :)

**Comment by ChrisNabold** [comment]
Dear Florentin,

 

Thank you for your Email. Finally I managed to run the EJML testcase. 

I installed Maven but I did not realize that I have to install the library ad a dependance.

Our comment regarding imports is always a good comment. I used the *option to avoid errors about missing imports

 

Thank you again

Best wishes

Chris

**Comment by lessthanoptimal** [comment]
Sounds like this has been resolved. @ChrisNabold do you have an example Maven build script that's simple which people could look at in the future?

**Comment by lessthanoptimal** [comment]
feel free to re-open if this isn't resolved.
