### ISSUE TITLE
class org.ejml.data.DMatrixRMaj cannot be cast to class org.ejml.data.DMatrixSparseCSC

### ISSUE THREAD

**Issue by edoardorealini** [lessthanoptimal/ejml#139]
Hello,

I am trying to build a DMatrixSparseCSC through a SimpleMatrix in which data is loaded as a 2D array of doubles generated from a png image. My goal is to store the png as a sparse matrix in a binary file. 

When I try to generate the sparse matrix by calling the method simpleMatrix.getDSCC() on an instance of SimpleMatrix I get the follwing exception: 
java.lang.ClassCastException: class org.ejml.data.DMatrixRMaj cannot be cast to class org.ejml.data.DMatrixSparseCSC 

Am I doing something wrong?

Many thanks,
ER

**Comment by FlorentinD** [comment]
`getDSCC` does not convert the inner matrix into a CSC matrix but only tries to cast it. It looks more of a convenience method if you know your internal matrix is of type CSC.

I think you should use `org.ejml.ops.DConvertMatrixStruct#convert(org.ejml.data.DMatrixRMaj, org.ejml.data.DMatrixSparseCSC, double)`. So use `simpleMatrix.get()` for the DMatrixRMaj, e.g., `var sparseMatrix = convert(simpleMatrix.get(), null, 1e-4)`

** I never worked with the SimpleMatrix interface but only directly with the concrete matrix types`

**Comment by lessthanoptimal** [comment]
Adding a nice early to use function to convert the internal matrix type wouldn't be a bad idea. Maybe something like:

```
SimpleMatrix converted = simpleMatrix.convertType(DMatrixSparseCSC.class);
SimpleMatrix converted = simpleMatrix.convertDDRM();
```

Other suggestions are welcomed.

**Comment by FlorentinD** [comment]
@lessthanoptimal you already implemented these methods in `org.ejml.ops.ConvertMatrixType#convert`. I opened a PR to fix the getters by implicitly converting to the required type.

@edoardorealini In the meantime you can simply use either  `org.ejml.ops.ConvertMatrixType#convert` or `SimpleMatrix.convertToSparse()`.

**Comment by lessthanoptimal** [comment]
resolved
