### ISSUE TITLE
Eigenvalue decomposition fails

### ISSUE THREAD

**Issue by user343** [lessthanoptimal/ejml#14]
Using version 0.29, eigenvalue decomposition fails for the below matrix (and similar ones):

    double[][] matrix = new double[][] {
        {1, 0, 0},
        {0.01, 0, -1}, 
        {0.01, 1, 0}
    };

**Comment by lessthanoptimal** [comment]
I'm assuming you're trying to get the eigen vectors also.  It works just fine if all you need are the eigenvalues.  That said, it shouldn't fail if you're requesting eigenvectors.  What it should do is find the eigenvector for the only real valued eigenvector.

This is definitely a bug and needs to be fixed.  Thanks for reporting it!  Hopefully it's something simple and I don't  need to spend a bunch of time refreshing my memory on how eigenvalue decomposition works.

**Comment by lessthanoptimal** [comment]
Fixed and will be included with version 0.30.  Spent a little bit of time on it and was able to guess what the problem was and fix it.  Didn't need to re-read the book on eigenvalue decomposition after all!
