### ISSUE TITLE
X^T X. for DDRM?

### ISSUE THREAD

**Issue by tr8dr** [lessthanoptimal/ejml#146]
I've been scouring the various dense matrix helper classes but have not come across a class with specializations for computing the Gramian matrix  X^T X.  This form occurs in OLS and many other scenarios.   Doing a X.transpose.mult(X) would be super expensive for a rectangular X of large size (where rows >> columns), whereas the product is a much smaller result.

Does this exist somewhere in the code and I have not come across it?

**Comment by lessthanoptimal** [comment]
[CommonOps_DDRM.multTransA(A,B,C)](http://ejml.org/javadoc/org/ejml/dense/row/CommonOps_DDRM.html#multTransA(T,T,T)) is probably what you want to use.

**Comment by tr8dr** [comment]
thx!
