### ISSUE TITLE
Compute number of solutions of linear system of equations

### ISSUE THREAD

**Issue by kamilwattoo** [lessthanoptimal/ejml#15]
System of linear equations may have unique solution, infinite solutions and no solution. When system is consistent it may have unique solution or infinite solutions and when system is inconsistent then there is no solution for system.

suppose I have this system and has solution x = 2 and library gives valid result.
2x = 4
3x = 6

On the other hand for below system of equations library gives 2.154 which is approximation of x and not a valid result because system does not has any solution at all.

2x = 5
3x = 6

Currently I am using [Rouché–Capelli theorem](https://en.wikipedia.org/wiki/Rouch%C3%A9%E2%80%93Capelli_theorem) to find number of solutions for given system. Due to machine precision and nearly singular values this sometimes do not yield valid result. It is also not efficient because it needs rank of augmented matrix. 

So using EJML how can I find number of solutions for given system of linear equations.

**Comment by lessthanoptimal** [comment]
SVD is typically used to determine if there is infinite solutions or one solution.  In the case where there is redundancy I believe it finds the solution which minimizes the error.  So to determine if there are no solutions you would have to plug the answer back into the original equation and see if there is a large error or not.
