### ISSUE TITLE
java.lang.NoSuchMethodError: org.ejml.UtilEjml.reshapeOrDeclare 

### ISSUE THREAD

**Issue by xishen** [lessthanoptimal/ejml#152]
I just downloaded the latest code and built and installed locally with maven. However when I ran my code, both Java 8 and 11 JVM crashed. Here is the stack dump: 
java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.lang.NoSuchMethodError: 'org.ejml.data.ReshapeMatrix org.ejml.UtilEjml.reshapeOrDeclare(org.ejml.data.ReshapeMatrix, org.ejml.data.ReshapeMatrix, int, int)'
    at org.ejml.dense.row.CommonOps_MT_FDRM.multTransB (CommonOps_MT_FDRM.java:142)
    at com.atg.Linear.ejmlCosineHalfBatch (Linear.java:79)
    at com.atg.Linear.main (Linear.java:183)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:829)

Any help?

**Comment by xishen** [comment]
I tried 0.40, 0.41 and 0.42-SNAPSHOT all failed but 0.39 worked.

**Comment by xishen** [comment]
checked the class file of UtilEjml (0.4x jar files )and no definition of reshapeOrDeclare was found.

**Comment by lessthanoptimal** [comment]
I'm seeing several variants of that function inside of [UtilEjml](https://github.com/lessthanoptimal/ejml/blob/ee02258e2c2bd06983064b778f458434033dc2d9/main/ejml-core/src/org/ejml/UtilEjml.java#L82) and it looks like they were last modified September 2020. Could you paste the code? Maybe the specific variant you're using got refactored.

**Comment by xishen** [comment]
The following is the code:
   `private static FMatrixRMaj ejmlCosineHalfBatch(float[] raw)
    {  
        FMatrixRMaj mat = FMatrixRMaj.wrap(SAMPLE_COUNT, FEATURE_COUNT, raw);  
        FMatrixRMaj result = new FMatrixRMaj(SAMPLE_COUNT, SAMPLE_COUNT);  
        CommonOps_MT_FDRM.multTransB(mat, mat, result);  
        CommonOps_FDRM.elementDiv(result, normMatrix(mat));  
        return result;  
    }`   

The exception is caused by  `CommonOps_MT_FDRM.multTransB(mat, mat, result)` it also fails if the function is changed to `CommonOps_FDRM.multTransB(mat, mat, result)`

P.S.: I didn't use `org.ejml.UtilEjml.reshapeOrDeclare` directly.

**Comment by lessthanoptimal** [comment]
For sake of completeness, can you show you Gradle / Maven / whatever dependency on EJML?

**Comment by xishen** [comment]
Here is the maven dependency:

 
    <dependency>

      <groupId>org.ejml</groupId>

      <artifactId>ejml-all</artifactId>

      <version>0.42-SNAPSHOT</version>

    </dependency>

And the JDK version:

<properties>

    <maven.compiler.source>1.8</maven.compiler.source>

    <maven.compiler.target>1.8</maven.compiler.target>
     ...

But EJML was built by JDK11.

**Comment by xishen** [comment]
From the dump of the JVM stack, the signature of the method is: 
`org.ejml.data.ReshapeMatrix org.ejml.UtilEjml.reshapeOrDeclare(org.ejml.data.ReshapeMatrix, org.ejml.data.ReshapeMatrix, int, int)`  I didn't find this variant inside of UtilEjml.

**Comment by xishen** [comment]
> I'm seeing several variants of that function inside of [UtilEjml](https://github.com/lessthanoptimal/ejml/blob/ee02258e2c2bd06983064b778f458434033dc2d9/main/ejml-core/src/org/ejml/UtilEjml.java#L82) and it looks like they were last modified September 2020. Could you paste the code? Maybe the specific variant you're using got refactored.

If I used the variant of the function that didn't exist directly the Java compiler would report an error rather than a runtime exception.

**Comment by xishen** [comment]
This is what I found within the class file of CommonOps_MT_FDRM.class:

        public static <T extends FMatrix1Row> T multTransB( T a, T b, @Nullable T output ) {
        output = reshapeOrDeclare(output, a, a.numRows, b.numRows);
        UtilEjml.checkSameInstance(a, output);
        UtilEjml.checkSameInstance(b, output);
        MatrixMatrixMult_MT_FDRM.multTransB(a, b, output);
        return output;
    }

The second line is the call site.

**Comment by xishen** [comment]
I've also found something is odd that the class file (UtilEjml.class) has no definition of any `reshapeOrDeclare()` variants. Looks like the java compiler has removed them Completely. Unlike the source code of [UtilEjml.java](https://github.com/lessthanoptimal/ejml/blob/ee02258e2c2bd06983064b778f458434033dc2d9/main/ejml-core/src/org/ejml/UtilEjml.java#L82), the first method in the class file is `checkSameInstance()` followed by `CheckSameShape()` instead of `reshapeOrDeclare()` 

Java compiler doesn't remove any code even it is unreachable. Maybe the version of ejml is messed up in my machine.

**Comment by lessthanoptimal** [comment]
That's really bizarre. Could there be a dependency on an ancient version of EJML hidden in the project?

**Comment by lessthanoptimal** [comment]
Is it possible to make a very simple project and reproduce this?

**Comment by xishen** [comment]
> Is it possible to make a very simple project and reproduce this?

you are right! ;-) Stanford NLP has introduced a implicit dependency on an old version (0.39) of EJML which messed up maven :-(  case closed!
