### ISSUE TITLE
SimpleMatrix concatenation ignores type of first matrix when resolving result type

### ISSUE THREAD

**Issue by JozsefKutas** [lessthanoptimal/ejml#156]
Hi,

I came across a bug when concatenating SimpleMatrix instances, where it seems the type of the first matrix is ignored:

```java
SimpleMatrix fscc = new SimpleMatrix(1, 1, MatrixType.FSCC);
SimpleMatrix ddrm = new SimpleMatrix(1, 1, MatrixType.DDRM);
System.out.println(fscc.concatColumns(ddrm).getType());  // this is DDRM
System.out.println(ddrm.concatColumns(fscc).getType());  // this is FSCC
System.out.println(ddrm.concatColumns().getType());  // also FSCC
```

The issue seems to be in the `specify0( SimpleBase a , SimpleBase ...inputs )` method of the `AutomaticSimpleMatrixConvert` class, which returns `specify(inputs)` when it should probably return `specify(array)`.

**Comment by lessthanoptimal** [comment]
Thanks for reporting this! I'll take a look into it in the next few days.
