### ISSUE TITLE
0 matrix non symmetric

### ISSUE THREAD

**Issue by HGuillemet** [lessthanoptimal/ejml#158]
A newly initialized matrix with only 0.0 si reported as non-symmetric by `isSymmetric`, due to the unchecked normalisation of the elements by `CommonOps_DDRM.elementMaxAbs(m)`.

**Comment by lessthanoptimal** [comment]
Verified and fixed. Avoids division now. Also checked to see if the bug was cut and pasted elsewhere and didn't find other instances. Thanks for reporting it!
