### ISSUE TITLE
Unit Test Failing

### ISSUE THREAD

**Issue by malcolmgreaves** [lessthanoptimal/ejml#16]
Hello!

I noticed that master is currently failing tests, and has been since April 2016:

https://travis-ci.org/lessthanoptimal/ejml/jobs/120376071

**Comment by lessthanoptimal** [comment]
A bug was discovered then so it was failing a while ago but just didn't know it was.  Unfortunately it's not going to be an easy big to fix.  Maybe when my work hours calm down again I can take a crack at it.

**Comment by lessthanoptimal** [comment]
Was able to fix it after only a few hours.  Think I got lucky.
