### ISSUE TITLE
MatrixIO.printJava should ignore default locale

### ISSUE THREAD

**Issue by HGuillemet** [lessthanoptimal/ejml#161]
`MatrixIO.printJava` formats numbers using `PrintStream.printf(format, x)`.
So if our default locale uses a comma for decimal separator, we end up with numbers not conforming to Java.
`printf` has an overload taking an explicit locale. I guess it's the one to use, specifying `Locale.US` or similar.

**Comment by lessthanoptimal** [comment]
@HGuillemet so is the issue that it's conforming to your locale or the issue that it is not conforming to your locale?

Either way, what I think you're requesting is a function like this:

` public static void print( PrintStream out, DMatrix mat, Local local, String format )
`
correct?

**Comment by ennerf** [comment]
Likely that it is conforming to the locale. I've run into this a few times on German systems that would print numbers in a format that Java fails to parse later on.

**Comment by HGuillemet** [comment]
Right. `printJava` conforms to my locale but it should not.
No need for a new function. printJava should be modified to ignore default locale (and use Locale.US for instance, or, probably better, the plain `Double.toString`/`Float.toString`  methods that will print all decimals).
I'd say it's a bug, not  a feature request.

**Comment by lessthanoptimal** [comment]
Just pushed the change to make it default to US. There's a static variable that you can change to change the local.

**Comment by lessthanoptimal** [comment]
FYI This fix is going to be released in 0.41.1

**Comment by HGuillemet** [comment]
Thank you for this fix.
I would probably have limited the fix to `printJava`.
For other output methods, which generate human-readable data,  It is normal to use the system default locale so that the comma character, but also for instance the thousand separator, correspond to what the local humans use.
Only `printJava` (and saveMatlab of course) generate data for machines which must conform to a standard.

Also you'll break more existing codes.

**Comment by lessthanoptimal** [comment]
I was considering that but decided to go for it being universally compatible by default. This way pasted output can be used by everyone. Doesn't seem to be any really clean option here. I guess I'll see if people complain. Now the JavaDoc should mention that static variable, which it currently doesnt.
