### ISSUE TITLE
MatrixIO.saveMatrixMarketD emits incorrect files (missing header)

### ISSUE THREAD

**Issue by alugowski** [lessthanoptimal/ejml#163]
`MatrixIO.saveMatrixMarketD` does write the MatrixMarket header line, so any files it generates cannot be read by other Matrix Market loaders.

This code:
```
    public static void writeMatrixMarket(DMatrixSparse mat, String filename) throws IOException {
        try (Writer writer = new FileWriter(filename)) {
            MatrixIO.saveMatrixMarketD(mat, "%.4e", writer);
        }
    }
```

Emits files like this:
```
% Matrix Market Coordinate file written by EJML 0.41
% printf format used '%.4e'
        7         7        12
        2         1 1.0000e+00
        4         1 1.0000e+00
...
```

It should first emit a header line similar to this:
```
%%MatrixMarket matrix coordinate real general
```
See https://math.nist.gov/MatrixMarket/formats.html

**Comment by lessthanoptimal** [comment]
https://github.com/lessthanoptimal/ejml/tree/feature/various

Does that fix it?

**Comment by alugowski** [comment]
I haven't run it, but it looks good!

**Comment by lessthanoptimal** [comment]
Can I close this ticket?

**Comment by alugowski** [comment]
yes
