### ISSUE TITLE
Adding better support for complex matrix to SimpleBase

### ISSUE THREAD

**Issue by lessthanoptimal** [lessthanoptimal/ejml#168]
Creating this issue from a list that @JozsefKutas posted in https://github.com/lessthanoptimal/ejml/issues/155

Complex matrix support is pretty limited, but maybe this is by design. There are no methods for adding/subtracting/multiplying/dividing by complex numbers, extracting the real/imaginary part, or taking the conjugate. It would also seem more natural for the complex entry setter to have signature SimpleMatrix#set(int row, int col, Complex_F64 complex) to match SimpleMatrix#get​(int row, int col, Complex_F64 output).

**Comment by lessthanoptimal** [comment]
@JozsefKutas For your comment about complex accessors, doesn't `get` and `set` already exist exactly as you described? Am I reading that wrong?

**Comment by lessthanoptimal** [comment]
- [x] Add stripRead and stripImaginary
- [x] Add conjugate and magnitude
- [x] Add fill complex
- [x] Add transposeConjugate
- [x] Add complex determinate
- [x] Update element accessors
- [x] Add user defined element wise operators
- [x] plus, minus, scale, complex

List of features to add

**Comment by JozsefKutas** [comment]
It's a minor issue, but it's similar to the original post in #155 about getting and setting rows/columns, where the getter and setter signatures don't match. At the moment the signatures are `SimpleMatrix#get​(int row, int col, Complex_F64 output)` and `SimpleMatrix#set​(int row, int col, double real, double imaginary)`. It means that when manipulating entries the user gets objects from the getter which they have to unpack when calling the setter, which is a bit clunky.

I don't think it's as significant as the row/column getter and setter issue though.

**Comment by JozsefKutas** [comment]
Thanks for looking into this btw. Let me know if you want any help working through the list.

**Comment by lessthanoptimal** [comment]
Ahhh I get it now. For accessing, would getReal() and getImaginary() also be useful?

**Comment by lessthanoptimal** [comment]
https://github.com/lessthanoptimal/ejml/tree/feature/simple_refresh

That's the branch I'm working in. Probably should have a different name since it's going to be just for complex ops

**Comment by JozsefKutas** [comment]
Yeah, I think having `getReal` and `getImaginary` would definitely be useful. I'll check out the branch tomorrow.

**Comment by lessthanoptimal** [comment]
https://github.com/lessthanoptimal/ejml/pull/171
