### ISSUE TITLE
Sparse Matrix

### ISSUE THREAD

**Issue by mroodschild** [lessthanoptimal/ejml#17]
Hello!
Currently I was reviewing many libraries. EJML, is by far the easiest and best designed. I think EJML, can become very accepted if contemplates Sparse Matrices, as they are widely used by the scientific community. Moreover, when the deep neural networks make heavy use of sparse matrices.
Thanks

**Comment by lessthanoptimal** [comment]
There is a chance that work on this might start late 2016 and early 2017 since it's needed for Sparse Bundle Adjustment.  You might want to check out https://github.com/jeffhain/ejml_mult_sparse I was unfortunately very busy when it was first presented to me and never got a chance to look at it.

- Which networks layers make use of sparse matrices?  I guess if it was ReLU followed by affine you could take advantage of the sparsity.
- You might want to check out [DeepBoof](https://github.com/lessthanoptimal/DeepBoof) it's another project of mine
- Which type of sparse matrix do you need?  There are several types.

**Comment by mroodschild** [comment]
Currently when working with deep networks, the coefficient sparse in a autoencoder, causes the outputs of the hidden layer are sparse, this output enters the next layer with a lot of zeros, depending on this ratio, 95% or 90% values are zero, and these are multiplied by dense matrices of the next layer. We can not say that there is a regular form of zeros, but it is important to have some generic multiplication operation.

Thanks for the info, I'll check matrix and the library.

**Comment by lessthanoptimal** [comment]
Could you look into which sparse data structures are typically used for this application?  The sparse structures for bundle adjustment tend to be highly structured.

**Comment by lessthanoptimal** [comment]
About a year ago (Jan 20160 Jeff Hain showed me his sparse matrix mult:

> In case you'ld be interested in integrating it into EJML,
> here is an EJML variant of a sparse matrix multiplication
> algorithm, for RowD1Matrix64F matrices:
> 
> https://github.com/jeffhain/ejml_mult_sparse
> 
> It can give great speed-ups, and it doesn't cost much to
> figure out whether it's worth to call it, yet it's much
> simpler than what I could find in papers.

Haven't been 100% sure how/if it should integrated in yet since there isn't anything very similar in the code yet.  Instead of just sitting on it I'm posting it here.

**Comment by lessthanoptimal** [comment]
Sparse matrix support is actually happening.  Had some time and implemented a bunch of operations up to solving triangular systems.  just need to get a decomposition working and it should be useful.  There might be a release soon with at least partial support.

**Comment by GeoffreyGuettier** [comment]
Hello,
I am using org.ejml:ejml-all:0.31 library.
It seems that set() method returns a wrong number.
Whatever is the value, myDMatrixSparseCSC.set(indexRow, indexColumn, VALUE) set indexColumn instead of VALUE

Moreover, is it possible to get row and column index for a non-zero value ?

Thank you for fix.

**Comment by lessthanoptimal** [comment]
Could you provide a code snippet that I can compile and test? Maybe the unit tests missed something.

set() and get() in CSC matrices are also very slow operations. If you need to construct a sparse matrix first create a DMatrixSparseTriplet the convert it into a CSC format. The documentation for sparse matrices is a bit poor at the moment. Once a solver is added (which is slowly being worked on) I'll make it much better.

For your last question. Do you mean that the matrix contains an element with a unique value (e.g. 2.324234) and you want to find it in the sparse matrix, then get the row and col of it?

**Comment by GeoffreyGuettier** [comment]
Hello,Thank you for responding.THis is my code : you can change each index by whatever you want instead of get it from a String[] and HashMap<String, Integer>.
public class MatrixManager {

    private static DMatrixSparseCSC X; // X=W1*W2
    
    public int vocabularyDimension;

    public void build_X(Collection<String[]> corpus) {

        /************scan corpus for having co-occurrency frequencies******************/
        X = new DMatrixSparseCSC(vocabularyDimension, vocabularyDimension, 0);
        int c;
        int w;
        int contextIndex;
        int targetIndex;
        //X.set(0,0,10); //TODO TEST that confirms bug DMatrixSparseCSC.set => set "0"
        //reading the corpus to have co-occurrence frequencies
        //and fill right part of X

        for (String[] tweetWords : corpus) {
            for (c = 0; c < tweetWords.length; c++) {
                if (vocabularyIndex.containsKey(tweetWords[c])) {
                    contextIndex = vocabularyIndex.get(tweetWords[c]);
                    for (w = 1; w < contextLenght + 1; w++) {
                        if ((c - w) >= 0 && vocabularyIndex.containsKey(tweetWords[c - w]) ) {
                            targetIndex = vocabularyIndex.get(tweetWords[c - w]);
                            if(contextIndex!=targetIndex) {
                            double freq = X.get(contextIndex, targetIndex) + 1;
                            X.set(contextIndex,targetIndex,freq); //TODO bug DMatrixSparseCSC.set
                            double result = X.get(contextIndex, targetIndex);
                            //System.out.println("[" + contextIndex + "] [" + targetIndex + "] " + result);
                            }
                        }
                        if ((c + w) < tweetWords.length && vocabularyIndex.containsKey(tweetWords[c + w])) {
                            targetIndex = vocabularyIndex.get(tweetWords[c + w]);
                            if(contextIndex!=targetIndex) {
                            double freq = X.get(contextIndex, targetIndex) + 1;
                            X.set(contextIndex,targetIndex,freq); //TODO bug DMatrixSparseCSC.set
                            double result = X.get(contextIndex, targetIndex);
                            //System.out.println("[" + contextIndex + "] [" + targetIndex + "] " + result);
                            }
                        }
                    }
                }
            }
        }
    }
}
 

    Le Jeudi 13 juillet 2017 16h40, Peter Abeles <notifications@github.com> a écrit :
 

 Could you provide a code snippet that I can compile and test? Maybe the unit tests missed something.set() and get() in CSC matrices are also very slow operations. If you need to construct a sparse matrix first create a DMatrixSparseTriplet the convert it into a CSC format. The documentation for sparse matrices is a bit poor at the moment. Once a solver is added (which is slowly being worked on) I'll make it much better.For your last question. Do you mean that the matrix contains an element with a unique value (e.g. 2.324234) and you want to find it in the sparse matrix, then get the row and col of it?—

**Comment by GeoffreyGuettier** [comment]
Hello, you can just try this :X = new DMatrixSparseCSC(10, 10, 0);
X.set(0,0,2);System.out.println(X.get(0,0));
And about row and colomn of a non zero element, i found a way but it is really not ergonomic to me :
int c;int c2;
int row;
int column = 0;
int nonZero_Number_For_Column_begin = 0;
int nonZero_Number_For_Column_end;

/*****************correction du modele pour les Xij non null (ou 0) *********/
for(c=1;c<X.col_idx.length;c++) {
    nonZero_Number_For_Column_end = X.col_idx[c];
    //System.out.println("nombre de non zero dans la colonne " + (nonZero_Number_For_Column_end - nonZero_Number_For_Column_begin));
    for(c2=nonZero_Number_For_Column_end-1;c2>=nonZero_Number_For_Column_begin;c2--) {
        row = X.nz_rows[c2];
        if(X.get(row,column)!=0) {gloVe_train(row,column);} //TODO condition if 0 due au bug DMatrixSparseCSC.set
    }
    column = column+1;
    nonZero_Number_For_Column_begin = nonZero_Number_For_Column_end;}

When do you think it can be fixed ? 

    Le Jeudi 13 juillet 2017 16h40, Peter Abeles <notifications@github.com> a écrit :
 

 Could you provide a code snippet that I can compile and test? Maybe the unit tests missed something.set() and get() in CSC matrices are also very slow operations. If you need to construct a sparse matrix first create a DMatrixSparseTriplet the convert it into a CSC format. The documentation for sparse matrices is a bit poor at the moment. Once a solver is added (which is slowly being worked on) I'll make it much better.For your last question. Do you mean that the matrix contains an element with a unique value (e.g. 2.324234) and you want to find it in the sparse matrix, then get the row and col of it?—

**Comment by GeoffreyGuettier** [comment]
EDIT : Finally i just used DSparseMatrixTriplet and it works and it is ergonomic to get index (for each DSparseMatrixTriplet.Element, there is row and column)

**Comment by lessthanoptimal** [comment]
I tested your example and there was a bug. The unit test for set() was bad which is how it was missed. It invoked set() twice on the same element. The first time you invoke set() it would assign the wrong value. Added your name to the change list for finding the bug.

**Comment by lessthanoptimal** [comment]
For your latest comment, are you talking about DSparseMatrixTriplet or DMatrixSparseCSC? If you think there's another bug another simple example would help again.

P.S. the latest SNAPSHOT has the fix or you can compile from the github SNAPSHOT code.

**Comment by lessthanoptimal** [comment]
Latest SNAPSHOT has good support for sparse matrix operations and includes solvers for cholesky, LU, and QR using direct methods. Closing this issue. Any bugs found in the sparse code or feature requests should be created with a new ticket.
