### ISSUE TITLE
Declare serial version uid in SimpleBase

### ISSUE THREAD

**Issue by joshmalina** [lessthanoptimal/ejml#18]
Without specifying the serial version, you can get version mismatch errors. Classes that extend Serializable should do this, with something like: 

ANY-ACCESS-MODIFIER static final long serialVersionUID = 42L;

in this file: https://github.com/lessthanoptimal/ejml/blob/2a2bfb58d789148d06fc002e7118e5f870012683/main/simple/src/org/ejml/simple/SimpleBase.java

**Comment by lessthanoptimal** [comment]
fixed in latest snapshot
