### ISSUE TITLE
innerProduct and innerProductSelfSymmetrical operation optimized for sparse vectors

### ISSUE THREAD

**Issue by spensonshih** [lessthanoptimal/ejml#180]
Hi,

This is a proposal to add `innerProduct` /  `innerProductSelfSymmetrical` operation optimised for sparse vectors.

The new version of `innerProduct` will be specialised to take in sparse vectors for `A` and `C`, and a matrix `B`.

scalar = A<sup>T</sup> * B * C

This is a common operation in portfolio risk modelling for computing variance or variance contributions based on a factor risk model. `A` and `C` represent exposures of a security or portfolio to risk factors, and `B` represents the symmetric and positive semi-definite covariance matrix of the risk factors. `B` is dense because factors are related, but `A` and `C` are sparse because individual securities or portfolios often only are exposed to a small fraction of the factors in the model, depending on their asset type. For example, stocks are not directly exposed to interest rates, while bonds are not directly exposed to the stock market (only indirectly). 

Shrinking the matrix is one option, but it is often not viable as the same matrix will be applied repeatedly to millions of securities and portfolios with varying sets of factors.

The current version of innerProduct iterates over the non-zero elements of the matrix, `B`, which is dense here and causes it be an expensive operation.  By providing a version of innerProduct that iterates over the non-zero elements of `A` and `C` instead, this would avoid a lot of unnecessary operations and have a significant performance improvement.

Here's what the implementation might look like:

```java
public static double innerProduct(DMatrixSparseCSC a, DMatrixD1 b, DMatrixSparseCSC c) { 
    double output = 0.0; 
    for (Iterator<DMatrixSparse.CoordinateRealValue> it1 = a.createCoordinateIterator(); it1.hasNext(); ) { 
        DMatrixSparse.CoordinateRealValue c1 = it1.next(); 
 
        double innerOutput = 0.0; 
        for (Iterator<DMatrixSparse.CoordinateRealValue> it2 = c.createCoordinateIterator(); it2.hasNext(); ) { 
            DMatrixSparse.CoordinateRealValue c2 = it2.next(); 
            innerOutput += c2.value * b.get(c1.row, c2.row); 
        } 
        output += c1.value * innerOutput; 
    } 
    return output; 
} 
```

Of course, we’d add checks for the input’s lengths.   

For `innerProductSelfSymmetrical`, this will be specialised to take in sparse vector `A`, and a positive semi-definite covariance matrix `B`. 

scalar = A<sup>T</sup> * B * A

In this implementation of `innerProductSelfSymmetrical`, utilising the symmetry, it will calculate the product using just the lower (or upper) triangle, multiply this by 2, then add to the product of the matrix diagonal.  This reduces the number of operations by almost half.  The `innerProductSelfSymmetrical` is a key speedup in my use-case for calculating standalone variance of potentially millions of securities.

Please let us know your thoughts on this enhancement.  We believe it will have wide utility and adoption in the financial space, and we have an implementation ready to contribute in a pull request if this aligns with your view of the project.

**Comment by michael-bowen-sc** [comment]
@lessthanoptimal  Any feedback or thoughts on this proposal?

**Comment by lessthanoptimal** [comment]
I was on vacation last week and catching up right now. Just wanted to chime in quickly. 

In concept I don't have any issue and can see it being useful. Could you create that pull request? Optimizing sparse code can be a bit tricky so I'll take a close look at it and create a few benchmarks. Thanks in advance for the contribution!

@spensonshih

**Comment by michael-bowen-sc** [comment]
> I was on vacation last week and catching up right now. Just wanted to chime in quickly.
> 
> In concept I don't have any issue and can see it being useful. Could you create that pull request? Optimizing sparse code can be a bit tricky so I'll take a close look at it and create a few benchmarks. Thanks in advance for the contribution!
> 
> @spensonshih

Amazing!  Thank you for circling back.

**Comment by spensonshih** [comment]
@lessthanoptimal , thank you for your help in getting the pull request merged.
