### ISSUE TITLE
MatrixFeatures_DDRM.isDiagonalPositive( DMatrixRMaj a ) returns true if diagonal elements are >= 0

### ISSUE THREAD

**Issue by TobiasLangner-TomTom** [lessthanoptimal/ejml#186]
[Javadoc](https://github.com/lessthanoptimal/ejml/blob/43b53a187a3599dac93e08deccc37d85cbdec9ba/main/ejml-ddense/src/org/ejml/dense/row/MatrixFeatures_DDRM.java#L553) and implementation contradict each other.

**Comment by lessthanoptimal** [comment]
Hrm. You're right. It should be '>' and not '>='. This is probably because the intent was that it should be '>='. Time to do some digging and see what will break if it's "fixed"

**Comment by lessthanoptimal** [comment]
https://github.com/lessthanoptimal/ejml/pull/187

That's the "fix" hopefully not too many people relied on the old behavior. Internally in EJML its only used to check covariance matrices.

@TobiasLangner-TomTom
