### ISSUE TITLE
ClassCastException from implementations of generic Matrix.copy() method

### ISSUE THREAD

**Issue by bjkeller** [lessthanoptimal/ejml#20]
At least a couple of the implementations of `Matrix.copy` (https://github.com/lessthanoptimal/ejml/blob/master/main/core/src/org/ejml/data/Matrix.java#L46) result in a `ClassCastException` in simple usage.

Examples are `org.ejml.data.FixedMatrix5_64F`
(https://github.com/lessthanoptimal/ejml/blob/master/main/core/src/org/ejml/data/FixedMatrix5_64F.java#L141) and `org.ejml.data.FixedMatrix6_64F` (https://github.com/lessthanoptimal/ejml/blob/master/main/core/src/org/ejml/data/FixedMatrix6_64F.java#L150)
which if used like this
```
FixedMatrix5_64F m = new FixedMatrix5_64F();
FixedMatrix6_64F copy = m.copy();
```
results in a `ClassCastException`.

For these implementations to work, the implementing class methods need to have covariant return types so that the type is restricted by the implementing class.  I don't think this is possible when `copy()` is generic.

(discovered with [Randoop](https://randoop.github.io/randoop))

**Comment by lessthanoptimal** [comment]
Sorry for taking so long to reply. From your sample code it appears that ClassCastException is the correct response.

FixedMatrix5_64F is a fixed sized matrix with 5 elements.
FixedMatrix6_64F is a fixed sized matrix with 6 elements.

They are different types of classes and you can't convert one into another that way. You would need to create a FixedMatrix6_64F and copy the elements from FixedMatrix5_64F into it.

I'm going to close this issue. Feel free to open it again if I missed something.
