### ISSUE TITLE
SimpleBase does not work when wrapping classes inherited from DMatrixRMaj

### ISSUE THREAD

**Issue by ennerf** [lessthanoptimal/ejml#22]
SimpleBase::bits() checks for class equality, i.e., "mat.getClass() == DMatrixRMaj.class", which prevents it from working with a sub class.

Was there a reason for doing this? If not, maybe that should be replaced with instanceof or isAssignableFrom()

**Comment by lessthanoptimal** [comment]
No good reason for that. Fixed in latest SNAPSHOT
