### ISSUE TITLE
Memory capacity used

### ISSUE THREAD

**Issue by GeoffreyGuettier** [lessthanoptimal/ejml#23]
Hello,

1. I would like to know how much Bytes are used for an element of a DMatrixSparseTriplet ? (non zero and zero).

2. I would like to know how much Bytes are used for a element of a SimpleMatrix ? (is it dimensionRow*dimensionColumn*16 Bytes for a double ?)

Thank you a lot for responding

**Comment by lessthanoptimal** [comment]
The [message board](https://groups.google.com/forum/#!forum/efficient-java-matrix-library-discuss) is a better place for these sorts of questions.

DMatrixSparseTriplet - Uses about 8+4+4+objectoverhead for each non-zero element. Zero elements require no memory.

DMatrixSparseCSC - Uses about 8+4+4 for non-zero element and is the sparse matrix you will use for most computations.

SimpleMatrix - Depends on the matrix type. The latest SNAPSHOT can sparse and dense matrices. By default it wraps a DMatrixRMaj

DMatrixRMaj - m*n*8 bytes where 'm' and 'n' are the number of rows and columns.

**Comment by GeoffreyGuettier** [comment]
Thank you for these informations.
I use DMatrixSparseTriplet because i need to know row & column of each element.
Is it possible to used There is an equal matrix with int values instead of double for DMatrixSparseTriplet ?

SimpleMatrix default use double right ? How can it uses 8 Bytes/element ?

Kind regards,
Geoffrey Guettier

**Comment by lessthanoptimal** [comment]
There's no integer equivalent of DMatrixSparseTriplet. Not very useful for linear algebra. There is a float version of it FMatrixSparseTriplet. The autocode generator has not been applied to sparse operations because it's still under development.

In java a double is [8-bytes](http://www.cafeaulait.org/course/week2/02.html).

**Comment by GeoffreyGuettier** [comment]
Oh yes my apologies ! I was thinking about 8+4+4... so there is no memory for index of row and column.

Geoffrey Guettier
