### ISSUE TITLE
DMatrixSparseTriplet : nz_data.length & nz_length

### ISSUE THREAD

**Issue by GeoffreyGuettier** [lessthanoptimal/ejml#24]
Hello, what is the difference between  nz_data.length & nz_length ?
Indeed, in my algorithm, I have different values for these parameters.

**Comment by lessthanoptimal** [comment]
nz_length is the actual number of non-zero elements. nz_data.length is the length of the data array.

The array can be reshaped() if that happens arrays are not deallocated but the size of the matrix changes. deallocating and reallocating memory is expensive in java.

**Comment by lessthanoptimal** [comment]
the message board is also the correct place to ask questions...

**Comment by GeoffreyGuettier** [comment]
Thank you.
I just use growData().
What am I supposed to use ?
nz_data.length or nz_length to have the correct number of non zero values (and to growData) ?

Geoffrey Guettier

**Comment by lessthanoptimal** [comment]
The [message board](https://groups.google.com/forum/#!forum/efficient-java-matrix-library-discuss) can be found there. It's better to post these sort of questions to make it easier for other people to find the answer.
