### ISSUE TITLE
Convex Solvers

### ISSUE THREAD

**Issue by gsaxena888** [lessthanoptimal/ejml#27]
I'm exploring EJML and OjAlgo. I'm trying to find out if EJML has either a built-in-solution or some 3rd party solution that they recommend to solve convex problems, specifically Quadratic problems with simple inequality constraints (ie min  ||Y - Ax||^2 with all x >= 0). For example, OjAlgo provides this: http://ojalgo.org/generated/org/ojalgo/optimisation/convex/ConvexSolver.html

(We don't need the ability to constrain the coefficients quadritcally, though. Also, we noticed that the  OjAlgo solver implements an iterative active set method, which is powerful for small matrixes. Ideally, we're looking for some sort of active-set / true newtonian (not pseudo newtonian) solver, as our matrixes are reasonably small (~20) but we have ~100 million such matrixes.)

**Comment by lessthanoptimal** [comment]
Should have replied to this a long time ago... Anyways, this would not go into EJML which is strictly linear algebra it would go into http://ddogleg.org which contains optimization routines. ddogleg does not contain constrained optimization methods currently. In the next month or two linear programming should be added. Other types of constrained optimization maybe added in the future but there's no schedule.
