### ISSUE TITLE
Using SimlpeMatrix or SimpleBase with other matrix types than RMaj

### ISSUE THREAD

**Issue by hageldave** [lessthanoptimal/ejml#28]
Hi,
so the wrap method of SimpleMatrix allows to wrap any instance of the Matrix interface, also the setMatrix method of SimpleBase allows to set any instance of that interface and sets up the correct SimpleOperations for a matrix type.
But in SimpleBase, casts to MatrixRMaj are all over the place as if only this type of matrix could be wrapped. This makes it impossible to use SimpleMatrix or SimpleBase for other matrix types. For example SimpleBase.set(int,int,double) or SimpleBase.scale(double) on a wrapped sparse matrix throw a ClassCastException because of this.

My question is, would it not be possible to get rid of these casts and use the SimpleOperations instead? Maybe this question was considered before and it is not possible or impacts performance too much or something.
If it is possbible I'm curious if this is going to be changed soon. Or maybe I can do it and provide you with a pull request of that ;) ?

**Comment by lessthanoptimal** [comment]
The most recent release is starting to head in that direction, but you're right most functions are hard coded for dense row major matrices. It's something that I would like in there but it's not high priority at the moment and it would be great if someone could submit a pull request with this feature!

Here's one possible way to do it.

- See if the passed in SImpleMatrix is the same type
  - Use reflection to look up the appropriate implementation of SimpleOperations
- If not the same type
  - Convert to the simplest common type
    - sparse to dense
    - float to double
    - Real to complex
  - Call the appropriate SimpleOperations

**Comment by lessthanoptimal** [comment]
In the next release most of the casts to MatrixRMaj should be gone. Already made a significant dent in removing them.

**Comment by lessthanoptimal** [comment]
New release is out and support has drastically improved. There's also auto type conversion. Simple but works well, unless you are using a sparse matrix. In that situation if you try to manipulate a sparse and dense matrix it will convert sparse matrix into a dense one which could cause a crash as it tries to use up all the memory on your computer.
