### ISSUE TITLE
Uploading artifacts to the Central Repository

### ISSUE THREAD

**Issue by RadixIsatidis** [lessthanoptimal/ejml#29]
The latest version in maven central repository is 0.30, now. Upload the newest version, please.

**Comment by lessthanoptimal** [comment]
Module names got changed to avoid potential conflicts. For the most part ejml- was added as a prefix. See http://ejml.org/wiki/index.php?title=Download for a list of the module names.

0.33 was uploaded to maven central earlier today and is live on maven central

http://central.maven.org/maven2/org/ejml/ejml-ddense/0.33/
