### ISSUE TITLE
SimpleMatrix polymorphism bug

### ISSUE THREAD

**Issue by mroodschild** [lessthanoptimal/ejml#30]
Hi there!
I'm using SimpleMatrix, and there is a little bug:

```
SimpleMatrix matrix = new SimpleMatrix(2, 3, true, 1, 2, 3, 4, 5, 6);

double[] a = matrix.getDDRM().getData(); //this doesn't work fine
```

SimpleMatrix takes by default float numbers. 

Is there a simple way to use double?

Thanks!

**Comment by lessthanoptimal** [comment]
I think I see what's going on. If you change that to 1.0, 2.0, ... etc it would use doubles. If you want to use floats and make it clear that you are using floats use 1.0f, 2.0f, ... etc.

In the next release I'm considering changing it from var-arg input to an array to get rid of this ambiguity.

**Comment by mroodschild** [comment]
Yes Peter!
Thanks!
