### ISSUE TITLE
Null pointer exception in SimpleBase.concatRows

### ISSUE THREAD

**Issue by prubin73** [lessthanoptimal/ejml#31]
Let row1, row3 and row5 be 1 x n instances of SimpleMatrix. The following correctly concatenates them into a 3 x n matrix:
```
    DMatrixRMaj cat = CommonOps_DDRM.concatRows(row1.getDDRM(), row3.getDDRM(), row5.getDDRM());
    SimpleMatrix combo = SimpleMatrix.wrap(cat);
```

However, the analogous approach working directly with SimpleBase fails:

`    SimpleMatrix c = row1.concatRows(row3, row5);`

causes a NullPointerException at line 1382 of SimpleBase.java.

Looking at lines 1380 and 1387 of SimpleBase, should "m[1]" be "m[i + 1]"?

**Comment by mroodschild** [comment]
Hello prubin73, try with:

```

public static void main(String[] args) {
        SimpleMatrix row1 = new SimpleMatrix(1, 4, true, 1.0, 2, 3, 4.0);
        SimpleMatrix row2 = new SimpleMatrix(1, 4, true, 5, 6, 7, 8.0);
        SimpleMatrix row5 = new SimpleMatrix(1, 4, true, 9, 10, 11, 12.0);

        row1.print();
        row2.print();
        row5.print();

        DMatrixRMaj cat = CommonOps_DDRM.concatRows(row1.getDDRM(), row2.getDDRM(), row5.getDDRM());
        SimpleMatrix combo = SimpleMatrix.wrap(cat);
        
        combo.print();
    }
```

but problably this maybe your problem:

https://github.com/lessthanoptimal/ejml/issues/30

**Comment by prubin73** [comment]
Thanks. I'm not sure #30 is the problem. Have a look at this chunk of code from SimpleBase.concatRows:

```
            DMatrixRMaj m[] = new DMatrixRMaj[A.length+1];
            m[0] = (DMatrixRMaj)mat;
            for (int i = 0; i < A.length; i++) {
                m[1] = A[i].getDDRM();
            }
```

Notice that m[0] is set (once) and m[1] is repeatedly overwritten, but m[2], m[3], ... are never set. My guess is that m[2] is registering as a null in line 2546 of CommonOps_DDRM.java, which is where the exception actually gets thrown.

**Comment by prubin73** [comment]
Thanks. I have a similar workaround in my code now.

**Comment by lessthanoptimal** [comment]
Thanks for finding this bug. There was a similar one in concatColumns() too. The fixes (and better unit tests) are in the latest SNAPSHOT.
