### ISSUE TITLE
Open an Image as a Matrix

### ISSUE THREAD

**Issue by mroodschild** [lessthanoptimal/ejml#33]
Hi Peter,

Is it possible to open an image as a Matrix?  I know that you have BoofCV, but it would be interesting to use the power of both.

Thanks

**Comment by lessthanoptimal** [comment]
You would need to write your own function to convert the formats. Easy to do with a gray scale image. An image with multiple bands won't translate well to EJML since it doesn't support N-dimensional arrays.

**Comment by mroodschild** [comment]
Thanks Peter! I will try

**Comment by lessthanoptimal** [comment]
Going to close this issue because it's a feature request for something that isn't going to be added to EJML.
