### ISSUE TITLE
SimpleMatrix implements Serializable but is not

### ISSUE THREAD

**Issue by fa-dev1** [lessthanoptimal/ejml#36]
However SimpleMatrix instances used to be serialized without problem in 0.28.
It now (0.34) has non-Serializable fields.
Either the classes of those members need to implement Serializable as well (which will propagate to many classes - e.g. everything that implements SimpleOperations), or the non-Serializable fields need to be qualified as transient. If they are transient, the Serialization/Deserialization will need to be implemented explicitly in order to re-create the non-serialized members on load - otherwise a loaded SimpleMatrix will not be usable.

**Comment by lessthanoptimal** [comment]
Fixed. Added a unit test which checks all supported matrix types within SimpleMatrix. Can you pull the latest SNAPSHOT and see if I covered your use case? Thanks.
