### ISSUE TITLE
ejml-ddense 0.34 references J2SE classes

### ISSUE THREAD

**Issue by kjkrum** [lessthanoptimal/ejml#37]
`ejml-ddense` and `ejml-fdense` version 0.34 reference `java.awt` and `javax.swing` packages, making them unusable (or at least requiring a workaround) in Android projects. It seems like a mixing of concerns for EJML to reference UI classes. Can this usage be avoided or split into another module?

**Comment by kjkrum** [comment]
I'm just including EJML as a dependency. The heavy handed solution is to disable lint. This isn't a big problem for me, more of a suggestion for improving the library.

**Comment by lessthanoptimal** [comment]
While swing code should be moved to a separate module, this hasn't been causing any problems in the past few years so I'm going to close the ticket. If someone was to add a `main/ejml-swing` package and move all this code there it will be accepted.
