### ISSUE TITLE
Cannot construct DMatrixSparseCSC with more than 50000 rows and columns

### ISSUE THREAD

**Issue by meyerphi** [lessthanoptimal/ejml#40]
When constructing a sparse matrix with the `DMatrixSparseCSC` class having 50000 rows and columns each, as follows, it fails with a `java.lang.NegativeArraySizeException`.
```
DMatrixSparseCSC a = new DMatrixSparseCSC(50000, 50000, 100000);
```
This happen as in `DMatrixSparseCSC.java`, in lines [92](https://github.com/lessthanoptimal/ejml/blob/c63c8526283f7fbb49eb7a7174d141e1f6f3b3d0/main/ejml-core/src/org/ejml/data/DMatrixSparseCSC.java#L92) and [334](https://github.com/lessthanoptimal/ejml/blob/c63c8526283f7fbb49eb7a7174d141e1f6f3b3d0/main/ejml-core/src/org/ejml/data/DMatrixSparseCSC.java#L334), there is the following statement:
```
arrayLength = Math.min(numRows*numCols, arrayLength);
```
With `numRows = 50000` and `numCols = 50000`, we have `numRows*numCols > Integer.MAX_VALUE`, so the value overflows to a negative value and the subsequent array initialization or access fails.

For my application (and scientific computing in general), sparse matrices having this theoretical full size, but with just a few non-zero entries, are common. The size in one dimension can even go up the millions. Therefore I would like them to be supported in EJML. I did some testing by fixing these two statements to handle the overflow, which worked together with the sparse matrix solver, but I do not know if anything else would break.

**Comment by lessthanoptimal** [comment]
Already found and fixed. I highly recommend switching to the SNAPSHOT. I've been applying it to a large scale problems and been making a lot of improvements.

**Comment by lessthanoptimal** [comment]
This is also a good time to submit any design changes or feature requests related to sparse matrices. I would be interested in knowing to how it compares to other libraries.

**Comment by meyerphi** [comment]
As for feature requests, currently I just need the solver(s) for the sparse matrixes, so I'm happy. I also haven't done any comparison with other libraries, the main reason for choosing EJML was that it is Java only. However, I just started using it, and will let you if I find or need anything.

**Comment by lessthanoptimal** [comment]
Pull again to get the fix for that.

**Comment by LsKoder** [comment]
This bug is on other constructors too.
For example, here:
https://github.com/lessthanoptimal/ejml/blob/SNAPSHOT/main/ejml-core/src/org/ejml/data/DMatrixRMaj.java

**Comment by lessthanoptimal** [comment]
Actually these are two very different issues. What is being discussed here is a flat out bug that would prevent you from declaring a valid sparse matrix. What you mentioned in the other ticket is that you are exceeding the limits of an array and depending on your perspective that's a design flaw in Java/EJML or user error.
