### ISSUE TITLE
SimpleMatrix.loadCSV method should be static

### ISSUE THREAD

**Issue by akinfermo** [lessthanoptimal/ejml#41]
Similarly to SimpleMatrix.loadBinary method, the SimpleMatrix.loadCSV method should be static. Is there any reason why it isn't?

https://github.com/lessthanoptimal/ejml/blob/c63c8526283f7fbb49eb7a7174d141e1f6f3b3d0/main/ejml-simple/src/org/ejml/simple/SimpleBase.java#L1311

**Comment by lessthanoptimal** [comment]
So that if you create your own derived class from SimpleMatrix the load will return the same type of matrix.

**Comment by akinfermo** [comment]
Ok. I see the tradeoff being made there. Any plans to provide a static method in a future release?

**Comment by lessthanoptimal** [comment]
Well I had decided to add a static function then found out that Java does not allow a static function to match the signature of a non-static function. I suppose I could already give it a different name...

**Comment by lessthanoptimal** [comment]
Javadoc has been updated to clarify that this function returns that it returns the same matrix type. Feel free to create a new issue if you want a static loadCSV or similar for SImpleMatrix
