### ISSUE TITLE
LevenbergMarquardt X and Y equal length constraint?

### ISSUE THREAD

**Issue by drauthev** [lessthanoptimal/ejml#43]
Hello,

I've been planning on using LevenbergMarquardt class for nonlinear optimization but I found an oddity browsing the code, in `configure()` method:
`if( Y.getNumRows() != X.getNumRows() ) {`
`throw new IllegalArgumentException("Different vector lengths"); }`
Why would you set an equality constraint between the number of inputs and outputs of a function? In a general case, a function can have arbitrary number of inputs and outputs independent of each other.

**Comment by lessthanoptimal** [comment]
I wrote that code a while ago and I'm not really sure. Just rewrote that implementation and now it's closer to a "real" implementation you might find in an optimization library while still simple. Take a look and let me know what you think. The latest SNAPSHOT has it.
