### ISSUE TITLE
Unsafe check on MaxInteger value on constructors

### ISSUE THREAD

**Issue by LsKoder** [lessthanoptimal/ejml#45]
On constructors, the following code is processed without a safe check:
`data = new double[ numRows * numCols ];`

In my experiments, some times it exceed Integer.MaxValue generating arrays with "random" size.

It could be better to check numRows * numCols result.
For example, I suggest to perform it before array generation:

```
if ( (numRows * numCols) != ((long)numRows * numCols))
   throw exception(..)
```

**Comment by lessthanoptimal** [comment]
I always considered negative array declaration exception to be an indication that you exceeded the limits of an array but having a more explicit and descriptive error message would be nice. This will be added in a future release.

**Comment by LsKoder** [comment]
In some cases I tested, `numRows * numCols` moltiplication provided a wrong **positive** value (not negative).
So, consider that NegativeException will not cover any cases.

Thanks

**Comment by lessthanoptimal** [comment]
I have this on the list for next release.

**Comment by lessthanoptimal** [comment]
done. sorry this issue got lost in the cracks. I'm going through the list and fixing as much as I can now.
