### ISSUE TITLE
DGrowArray::grow() does not set length

### ISSUE THREAD

**Issue by ennerf** [lessthanoptimal/ejml#51]
`DGrowArray::grow` increases the size of the array, but does't update the internal length field.

https://github.com/lessthanoptimal/ejml/blob/master/main/ejml-core/src/org/ejml/data/DGrowArray.java#L59-L64

**Comment by lessthanoptimal** [comment]
Looking at the function, I believe it's poorly named. growArray() with a flag would be better. reshape with a flag to preserve values would be a better fit I believe.

**Comment by lessthanoptimal** [comment]
I've attempted to address this issue by renaming it to growInternal() and adding comments to the JavaDoc. Feel free to reopen if you see an issue or better way.
