### ISSUE TITLE
How should EJML be referenced?

### ISSUE THREAD

**Issue by mroodschild** [lessthanoptimal/ejml#53]
Hello Peter.

I am working to present a paper about Froog Neural Network, it is the neural network that I am developing, I would like to reference your work in EJML. How could I do it?
I greet you attentively.

PD: Wishing me luck LOL.

**Comment by lessthanoptimal** [comment]
I think something like this

@software{ejml,
author =   {Peter Abeles},
title =    {Efficent Java Matrix Library},
url = {https://ejml.org},
version = {0.37.1},
date = {2019}
}

https://superuser.com/questions/8743/how-do-i-cite-software-in-latex

I really should publish a paper on EJML

**Comment by mroodschild** [comment]
Thanks Peter! I'll keep you informed
