### ISSUE TITLE
Initializing sparse matrix triplets

### ISSUE THREAD

**Issue by szarnyasg** [lessthanoptimal/ejml#54]
While working on our graph analyzer - a followup of the project mentioned in #49 - I found that class [`DMatrixSparseTriplet`](http://ejml.org/javadoc/org/ejml/data/DMatrixSparseTriplet.html) provides both the [`set(row, col, value)`](http://ejml.org/javadoc/org/ejml/data/DMatrixSparseTriplet.html#set-int-int-double-) and the [`addItem(row, col, value)`](http://ejml.org/javadoc/org/ejml/data/DMatrixSparseTriplet.html#addItem-int-int-double-).
The difference between these is not clear from the documentation.

It seems to me that `addItem` is the one to use and `set` should be avoided as it is significantly slower. Is this observation correct?

**Comment by lessthanoptimal** [comment]
you are correct that you should use addItem(). Maybe a better name would be push(). I've updated the JavaDoc. Could you check it out and tell me if that clarifies the behavior of these functions?

**Comment by szarnyasg** [comment]
Thanks, the new docs helped me clarify what's going on. A minor remark: there are some double dot characters (`row index..`), but otherwise, this is a great improvement.
