### ISSUE TITLE
ejml on java 1.7

### ISSUE THREAD

**Issue by fcampos** [lessthanoptimal/ejml#62]
Hello,
As I understand, ejml runs on jre 1.8 and beyond. However, I am developing an application to run on jre 1.7. Is there a previous release of ejml that is compatible with java 1.7? If so, is there a download link for it?

Many thanks!

**Comment by szarnyasg** [comment]
@fcampos the last version compatible with Java 1.7 was [v0.33](https://mvnrepository.com/artifact/org.ejml/ejml-core/0.33).
The Java version was chaged by commit 491ac4d8573c74cf5f1d3c098180be4a3c98263c.

**Comment by lessthanoptimal** [comment]
yep that's correct. I've also updated the FAQ. @fcampos you're not the first person to ask this question. I feel sorry for everyone stuck on ancient versions of Java.
