### ISSUE TITLE
Multiplication operation is yielding wrong result

### ISSUE THREAD

**Issue by 4kills** [lessthanoptimal/ejml#63]
The following method:
org.ejml.dense.fixed.CommonOps_DDF3.mult(org.ejml.data.DMatrix3x3 a, org.ejml.data.DMatrix3 b, org.ejml.data.DMatrix3 c) 
is yielding a wrong result for the second component of the resulting vector (c.a2).

See the following code snippet and output for proof. Performing the same calculation with two SimpleMatrices yields the right result. 

This shows the code and the contents of Matrix Rz and Vector rotated before multiplying
![image](https://user-images.githubusercontent.com/30271713/65802331-ab23fc00-e17b-11e9-9ffa-1319865862a4.png)

This shows the result for multiplication with DDF3 mult (first vector) and with simplematrix (second vector)
![image](https://user-images.githubusercontent.com/30271713/65802453-00600d80-e17c-11e9-987f-2cf4bdcf5a78.png)

**Comment by lessthanoptimal** [comment]
sorry for slow response. Could you post the exact code you used instead of screenshots?

**Comment by 4kills** [comment]
I should have posted code right away, sorry for that. 
Here it is: 

```java
import org.ejml.data.DMatrix3;
import org.ejml.data.DMatrix3x3;
import org.ejml.simple.SimpleMatrix;

public class EjmlMultIssue {
    private static final double[][] arrA =
            {
                    {1.1, 1.2, 1.3},
                    {2.1, 2.2, 2.3},
                    {3.1, 3.2, 3.3},
            };

    private static final double[][] arrV =
            {
                    {1.0},
                    {2.0},
                    {3.0},
            };

    public static void main(String... args) {
        SimpleMatrix simpleA = new SimpleMatrix(arrA);
        SimpleMatrix simpleV = new SimpleMatrix(arrV);

        DMatrix3x3 denseA = new DMatrix3x3(arrA[0][0], arrA[0][1], arrA[0][2],
                arrA[1][0], arrA[1][1], arrA[1][2],
                arrA[2][0], arrA[2][1], arrA[2][2]);
        DMatrix3 denseVecV = new DMatrix3(arrV[0][0], arrV[1][0], arrV[2][0]);

        // both matrices are the same
        simpleA.print();
        denseA.print();

        // both vectors are the same
        simpleV.print();
        denseVecV.print();


        (simpleA.mult(simpleV)).print(); // yields correct result

        naiveMatrixVecMult(denseA, denseVecV).print(); // yields correct result albeit very slow

        org.ejml.dense.fixed.CommonOps_DDF3.mult(denseA, denseVecV, denseVecV); // yields WRONG result.
        denseVecV.print(); // first component (denseVecV.a1) is calculated correctly tho.
    }

    // a naive approach to matrix multiplication as specified by the mathematical definition of dot product matrix mult
    private static DMatrix3x3 naiveMatrixMult(DMatrix3x3 a, DMatrix3x3 b) {
        DMatrix3x3 c = new DMatrix3x3();

        for (int i = 0; i < a.getNumRows(); i++) {
            for (int j = 0; j < b.getNumCols(); j++) {
                for (int k = 0; k < a.getNumCols(); k++) {
                    c.set(i, j, c.get(i, j) + a.get(i, k) * b.get(k, j));
                }
            }
        }

        return c;
    }

    // just for converting
    private static DMatrix3 naiveMatrixVecMult(DMatrix3x3 a, DMatrix3 v) {
        DMatrix3x3 b = new DMatrix3x3();
        b.a11 = v.a1;
        b.a21 = v.a2;
        b.a31 = v.a3;
        b = naiveMatrixMult(a, b);
        return new DMatrix3(b.a11, b.a21, b.a31);
    }
}
```

I have also calculated the product by hand and with this tool:
[https://matrixcalc.org/en/#%7B%7B11/10,6/5,13/10%7D,%7B21/10,11/5,23/10%7D,%7B31/10,16/5,33/10%7D%7D%2A%7B%7B1%7D,%7B2%7D,%7B3%7D%7D](url)

**Comment by lessthanoptimal** [comment]
The problem was that you passed in the same vector for input an output. As it performs the matrix multiplication it's being modified. SimpleMatrix avoids that by creating a new instance and basically simplified memory management, hence it's name. Ditto for your naive implementation.

Since very few matrix operations can performed using the same matrix as input and output the default behavior is that unless the JavaDoc says it's ok it isn't. Having said that, for fixed sized matrices it really wouldn't be a big performance hit if it did create a local copy on the stack.

**Comment by lessthanoptimal** [comment]
Added some checks to 0.39
