### ISSUE TITLE
solving sparse linear systems

### ISSUE THREAD

**Issue by fcampos** [lessthanoptimal/ejml#65]
Hello,
In a simulation software I need solve a sparse linear system repeatedly with the same A matrix.
I believe the recommended way of solving sparse linear systems is to use a solver of the class  LinearSolverFactory_DSCC, However, in the javadoc I came accross the class LinearSolverLu_DSCC, which intrigued me.
Is LinearSolverLu_DSCC a lower level class used by LinearSolverFactory_DSCC (assuming the LU method is chosen)? 
If not, is there any benefit of using LinearSolverLu_DSCC instead of LinearSolverFactory_DSCC?

Many thanks

**Comment by lessthanoptimal** [comment]
I recommend using the factory. Right now it will return the same class. However, specific implementations tend to get refactored or changed. If you use the factory you should be spared from all the pain associated with that. Now if you wanted to do a trick using the solver's internal data structures that's a good reason to  use it directly.
