### ISSUE TITLE
./gradlew oneJar issue

### ISSUE THREAD

**Issue by liuyang0717** [lessthanoptimal/ejml#69]
> Task :oneJarBin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':oneJarBin' (type 'Jar').
> No value has been specified for property 'archiveFile'.

**Comment by lessthanoptimal** [comment]
Fixed. Thanks for reporting the problem!

https://github.com/lessthanoptimal/ejml/commit/48f20d07185581b4aebcac2205b8764f81662d78
