### ISSUE TITLE
Maven not updating to newest version of ejml

### ISSUE THREAD

**Issue by kuliy45** [lessthanoptimal/ejml#7]
Ever since you guys switched to github from google code, your maven repository hasn't been updated.

http://mvnrepository.com/artifact/com.googlecode.efficient-java-matrix-library/ejml

**Comment by lessthanoptimal** [comment]
The group ID changed.  Try using the following instead:

<dependency>
  <groupId>org.ejml</groupId>
  <artifactId>all</artifactId>
  <version>0.28</version>
</dependency>
