### ISSUE TITLE
A Javadoc error

### ISSUE THREAD

**Issue by LDA111222** [lessthanoptimal/ejml#70]
![image](https://user-images.githubusercontent.com/46706466/85924371-78529400-b8c4-11ea-8d0c-1e47ab24d715.png)
CommonOps_DDRM.elementExp() uses Math.exp() instead of Math.log().

**Comment by Alexhaoge** [comment]
In Javadoc, it is log.
http://ejml.org/javadoc/org/ejml/dense/row/CommonOps_DDRM.html#elementExp(org.ejml.data.DMatrixD1,org.ejml.data.DMatrixD1)
In source code, it is clearly exp function.
https://github.com/lessthanoptimal/ejml/blob/ce37268e48d0a1aaa627982ee748b98e5f172c19/main/ejml-ddense/src/org/ejml/dense/row/CommonOps_DDRM.java#L1761

The similar issues also appear in **[CommonOps_FDRM.elementExp](http://ejml.org/javadoc/org/ejml/dense/row/CommonOps_FDRM.html#elementExp(org.ejml.data.FMatrixD1,org.ejml.data.FMatrixD1))**

**Comment by Alexhaoge** [comment]
In Javadoc, it is log.
http://ejml.org/javadoc/org/ejml/dense/row/CommonOps_DDRM.html#elementExp(org.ejml.data.DMatrixD1,org.ejml.data.DMatrixD1)
In source code, it is clearly exp function.
https://github.com/lessthanoptimal/ejml/blob/ce37268e48d0a1aaa627982ee748b98e5f172c19/main/ejml-ddense/src/org/ejml/dense/row/CommonOps_DDRM.java#L1761

The similar issue also appears in **[CommonOps_FDRM.elementExp](http://ejml.org/javadoc/org/ejml/dense/row/CommonOps_FDRM.html#elementExp(org.ejml.data.FMatrixD1,org.ejml.data.FMatrixD1))**

**Comment by lessthanoptimal** [comment]
I'll fix this today. Thanks for reporting it. Looks like a cut and paste error.

**Comment by lessthanoptimal** [comment]
Fixed. A little bit late but it's in the SNAPSHOT branch now.
