### ISSUE TITLE
Example using Semirings

### ISSUE THREAD

**Issue by lessthanoptimal** [lessthanoptimal/ejml#82]
Simple example showing how to use Semirings. Preferably not something which is too abstract that you need to be an expert in the field to understand what's going on.

**Comment by lessthanoptimal** [comment]
Any ideas?  @FlorentinD @breandan @szarnyasg @maxindelicato

**Comment by maxindelicato** [comment]
My primary use-case is their use in graph algorithms, of which the most well-known standard is GraphBLAS: [http://graphblas.org/index.php?title=Graph_BLAS_Forum](http://graphblas.org/index.php?title=Graph_BLAS_Forum); also, see here for further actionable details: [https://www.mit.edu/~kepner/GraphBLAS/GraphBLAS-Math-release.pdf](https://www.mit.edu/~kepner/GraphBLAS/GraphBLAS-Math-release.pdf). Perhaps some simple BFS examples could work? Or something along those lines?

**Comment by FlorentinD** [comment]
I agree bfs is a good example. 
I have some first bfs implementations on my fork in the mask branch (working but definitely not perfect) under BFS_DSCC.
As the branch name indicates, these implementations also include masks. 
However they might be a good starting point.

Shortest path algorithm might also be a good choice to show different semirings

**Comment by FlorentinD** [comment]
And a really simple example is basically in my matrix vector test, which are one bfs iteration. E.g the elements in the vector represent the starting nodes and the matrix the adjacency matrix of a graph
