### ISSUE TITLE
Generating large sparse random matrices seems to be very slow

### ISSUE THREAD

**Issue by FlorentinD** [lessthanoptimal/ejml#98]
Recently I introduced `generateUniform` for larger matrices (#95).
I should have added a benchmark for larger dimension, as it turns out, that its actually very slow.
For a matrix of `10^5 x 10^5` it took 10s on my machine...

One idea would be to parallelize the matrix creation.
Additionally having a benchmark, which compares `rectangle()` with `generateUniform()` might be useful.
As I need it for my personal benchmarks, I plan to resolve this issue myself.

Maybe someone has some additional ideas on how to improve the current implementation.

**Comment by ennerf** [comment]
Skimming through the linked code, I think two easy wins could be:

(1) change `BitSet` to `boolean[]`. It uses more memory, but the performance should be quite a bit better.

(2) replace `AtomicInteger` with a for loop over the array or a custom Int wrapper class (example below). Atomic* adds a lot of unnecessary synchronization overhead.

```java
static class IntHolder {
  int value;
}

IntHolder i = new IntHolder();
int index = i.value++;
```

**Comment by lessthanoptimal** [comment]
As an lower bound have you tried to see how fast it is to just generate random numbers without checking to see if they are legal? The other thing is to look at the other library that inspired this and use the same approach (don't copy the code though) if it's fast.

**Comment by FlorentinD** [comment]
Initial timing:
```
Dim 1000 avgEntries 4 generateUniform = 112 generateRectangle = 43
Dim 1000 avgEntries 8 generateUniform = 128 generateRectangle = 5
Dim 10000 avgEntries 4 generateUniform = 9835 generateRectangle = 195
Dim 10000 avgEntries 8 generateUniform = 9138 generateRectangle = 90
```

After using boolean[] and normal integer instead atomic:
```
Dim 1000 avgEntries 4 generateUniform = 88 generateRectangle = 31
Dim 1000 avgEntries 8 generateUniform = 75 generateRectangle = 5
Dim 10000 avgEntries 4 generateUniform = 8827 generateRectangle = 185
Dim 10000 avgEntries 8 generateUniform = 8746 generateRectangle = 90
```
-> improved a bit

**Seeing the actual bug: `boolean dropRows = (numRows/(float)nzEntriesPerColumn) > 0.5;`
It should be `boolean dropRows = ((float)nzEntriesPerColumn/numRows) > 0.5;`**

```
Dim 1000 avgEntries 4 generateUniform = 5 generateRectangle = 33
Dim 1000 avgEntries 8 generateUniform = 4 generateRectangle = 3
Dim 10000 avgEntries 4 generateUniform = 4 generateRectangle = 216
Dim 10000 avgEntries 8 generateUniform = 5 generateRectangle = 106
```

So it dropped f.i. 99% of the rows instead of just selecting the 1% ...

Of course these results have to be taken not very representative, as they are only run once for every configuration

**Comment by FlorentinD** [comment]
@lessthanoptimal In my benchmarks I changed to using the generator from the other library, so I knew it could be fast

**Comment by lessthanoptimal** [comment]
That's a big improvement! I'll test it in a few hours after work.

**Comment by lessthanoptimal** [comment]
Left a couple of comments. I also just push a fix for the CI issue. If a unit test fails it will no longer be ignored. I'll probably be spamming myself in the future since I get an e-mail when a build fails.

**Comment by lessthanoptimal** [comment]
merged
